# fly.toml app configuration file generated for backend-lively-wind-8008 on 2025-02-13T09:08:45-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-lively-wind-8008'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
